### PR TITLE
Correcting the default version numbers for a number of messages that …

### PR DESCRIPTION
**Pull request by adamrankin**
…should have version 2 by default.

Added base classes to simplify future addition of RTS, STT, STP, and GET messages.

Moving capabilities to v1 section as per the specification.

### CODE REVIEW

**Comment by adamrankin** [comment]
@lassoan There we go! Good idea, much cleaner. Sorry!

**Comment by lassoan** [comment]
Thanks Adam.

Why do we need all these new base classes?

**Comment by adamrankin** [comment]
Proper structure. Anything in common to all the GET, STT, STP, and RTS messages are initialized in the base class.

**Comment by lassoan** [comment]
I only see this->m_Version initialized in these base classes. But I guess that should be rather initialized in the common message base class.

**Comment by adamrankin** [comment]
For now, yes, but this establishes the infrastructure.

**Comment by lassoan** [comment]
Why m_Version is not specified in the common message base class?

What do you envision to put in the created intermediate base classes? Usually there is not much in common things between GET_, RTS_ and actual data messages.

**Comment by adamrankin** [comment]
Because m_Version is dependent on when the message was introduced. I
envision the final sent version as a parameter to the factory so that it
knows how to construct the message

**Pull request merged**
